version: '3.8'

services:
  bff:
    build:
      context: .
      dockerfile: ./bff/Dockerfile
    env_file:
      - ./bff/.env
    ports:
      - "5000:5000"

  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    env_file:
      - ./front/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - bff
